### ISSUE TITLE
Could not resolve all task dependencies for configuration ':sample:releaseCompileClasspath'.

### ISSUE THREAD

**Issue by PongPloy2016** [TutorialsAndroid/crashx#1]
hi bro i ran app in versions  android 21  error  

Could not determine the dependencies of task ':sample:compileReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':sample:releaseCompileClasspath'.
   > Could not resolve project :library.
     Required by:
         project :sample
      > Unable to find a matching configuration of project :library: None of the consumable configurations have attributes.

![Screen Shot 2562-04-02 at 17 46 01](https://user-images.githubusercontent.com/8625469/55396918-3c206e80-556f-11e9-9a42-de586086f5db.png)

Please Help :

**Comment by TutorialsAndroid** [comment]
I am not getting the issue you said can you provide me the stack trace

**Comment by TutorialsAndroid** [comment]
I got the issue you said and I will soon update this library.

**Comment by TutorialsAndroid** [comment]
> 
> 
> hi bro i ran app in versions android 21 error
> 
> Could not determine the dependencies of task ':sample:compileReleaseJavaWithJavac'.
> 
> > Could not resolve all task dependencies for configuration ':sample:releaseCompileClasspath'.
> > Could not resolve project :library.
> > Required by:
> > project :sample
> > > Unable to find a matching configuration of project :library: None of the consumable configurations have attributes.
> 
> ![Screen Shot 2562-04-02 at 17 46 01](https://user-images.githubusercontent.com/8625469/55396918-3c206e80-556f-11e9-9a42-de586086f5db.png)
> 
> Please Help :

The issue you describe was not found. when i was testing this library.The library is working perfectly as it.But still i have made a new version of this library **v15.4.19**

**Comment by PongPloy2016** [comment]
Ok bro Thank you .  to . answer
