### ISSUE TITLE
Logo Design For Crax

### ISSUE THREAD

**Issue by zularizal** [TutorialsAndroid/crashx#2]
Hi @TutorialsAndroid , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by TutorialsAndroid** [comment]
> Hi @TutorialsAndroid , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

Thank you for your interest in my projects.I want a logo  for my projects can you do this for me.
