### ISSUE TITLE
minSdkVersion +More customizable

### ISSUE THREAD

**Issue by rrreza** [TutorialsAndroid/crashx#3]
Hello
this is a good tools but:
1- Min SDK: in Arsenal min sdk is 15  (https://android-arsenal.com/details/1/7581)
but in your library is 21 (minSdkVersion 21)
`ERROR: Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.github.TutorialsAndroid:crashx:v4.0.19] C:\Users\Reza\.gradle\caches\transforms-2\files-2.1\3fdaec2313496edb98c5fbeefb1fde92\crashx-v4.0.19\AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.developer.crashx" to force usage (may lead to runtime failures)`

2-I do not find Function to change background color and text message and button text. (I know we can use own Activity)

**Comment by rrreza** [comment]
You use `requireNonNull` and must be minSdkVersion 19 but you can use alternative function for other api

**Comment by TutorialsAndroid** [comment]
Sorry in android arsenal by mistake we have puten min sdk version 15. but the library uses min sdk version 21. as our all android library uses min sdk version 21 only. and if you want to change background color and text message then you can use custom view. our all libraries are made for kinda debate app

> 
> 
> You use `requireNonNull` and must be minSdkVersion 19 but you can use alternative function for other api.
