### ISSUE TITLE
This library is a plagiarism

### ISSUE THREAD

**Issue by jakoss** [TutorialsAndroid/crashx#4]
Original repository can be found here: https://github.com/Ereza/CustomActivityOnCrash

@TutorialsAndroid anyone hiring you after reviewing somebody else's code?

**Comment by TutorialsAndroid** [comment]
> Original repository can be found here: https://github.com/Ereza/CustomActivityOnCrash
> 
> @TutorialsAndroid anyone hiring you after reviewing somebody else's code?

Go through original then. We are using this library for personal use. because the original library is not very up-to-date with the latest dependencies. its last commits are 5 months ago. as you wish you can use the original one.

**Comment by jakoss** [comment]
You can't just take somebody else's code and publish it as your own. At least what you should do it acknowledge original author. What you do here is unethical, illegal and just plainly rude. You want to update the library? No problem, do fork, do pull request. What you don't do is steal code as your own. Shame.

**Comment by jakoss** [comment]
https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

This is summary of the licence which you copied as well, but you don't seem to respect it at all. You are obliged to include original copyright of the library. You are obliged to include a notice and state changed made to the library. You did none of those while posing as a library author. That's clearly illegal, i reported you to the original author. It's up to him if he wants to take this further. This practice is a stain on open source community. Shame.

**Comment by fukemy** [comment]
he steal other code
